---
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - AWS_DEFAULT_REGION=eu-north-1
install:
  - pip install -r requirements.txt
script:
  - yamllint ./template.yaml
  - sam validate -t ./template.yaml
after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "AWS SAM template validated"
