---
language: python
python:
  - "3.6"
services:
  - docker
env:
  global:
    - AWS_DEFAULT_REGION=eu-north-1
install:
  - pip install -r requirements.txt
script:
  - "./travis/lint-validate.sh"
  - aws cloudformation package --template-file ./template.yaml --s3-bucket aws-sam-templates-eu-north-1 --output-template-file packaged-template.yaml
jobs:
  include:
    - stage: deploy-dev
      script: aws cloudformation deploy --template-file packaged-template.yaml --stack-name dev --capabilities CAPABILITY_IAM
stages:
  - name: deploy-dev
    if: branch = dev
after_success:
  - echo "Success!"
