---
language: python
cache: pip
python:
  - "3.6"
services:
  - docker
env:
  global:
    - AWS_DEFAULT_REGION=eu-north-1
    - TEST_ENV=true
install:
  - pip install -r requirements.txt
  - pip install awscli aws-sam-cli --upgrade
before_script:
  - ./travis/create-test-env.sh
  - sleep 5
script:
  - ./travis/lint-validate.sh
  - py.test ./tests/tavern/test_adventurio.tavern.yaml
  - aws cloudformation package --template-file ./template.yaml --s3-bucket aws-sam-templates-eu-north-1 --output-template-file packaged-template.yaml
deploy:
  - provider: script
    script: aws cloudformation deploy --template-file packaged-template.yaml --stack-name adventurio-dev --capabilities CAPABILITY_IAM
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: aws cloudformation deploy --template-file packaged-template.yaml --parameters ParameterKey=Stage,ParameterValue=prod --stack-name adventurio-prod --capabilities CAPABILITY_IAM
    skip_cleanup: true
    on:
      branch: master
after_success:
  - echo "Success!"
