---
language: python
cache: pip
python:
  - "3.6"
services:
  - docker
env:
  global:
    - AWS_DEFAULT_REGION=eu-north-1
install:
  - pip install -r requirements.txt
  - pip install awscli aws-sam-cli --upgrade
script:
  - ./travis/lint-validate.sh
  - . ./travis/set-deploy-variable.sh
  - aws s3 cp ./specs/openapi.yaml s3://aws-sam-templates-eu-north-1/openapi-template/openapi.yaml
  - aws cloudformation package --template-file ./template.yaml --s3-bucket aws-sam-templates-eu-north-1 --output-template-file packaged-template.yaml
  - aws cloudformation deploy --template-file packaged-template.yaml --stack-name $STACKNAME --capabilities CAPABILITY_IAM

after_success:
  - echo "Success!"
