---
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Enter 'dev' or 'prod'. Default 'dev'.
Resources:
  AdventurioApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}
      DefinitionBody:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: s3://aws-sam-templates-eu-north-1/openapi-template/openapi.yaml
  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "get-games-function-${Stage}"
      Runtime: python3.7
      Handler: index.handler
      CodeUri: ./lambda/get-games/
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AdventurioApiGateway
            Path: /games
            Method: GET
  PostGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "post-games-function-${Stage}"
      Runtime: python3.7
      Handler: index.handler
      CodeUri: ./lambda/post-games/
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AdventurioApiGateway
            Path: /games
            Method: POST
  GetGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "get-game-function-${Stage}"
      Runtime: python3.7
      Handler: index.handler
      CodeUri: ./lambda/get-game/
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AdventurioApiGateway
            Path: /games/{gameId}
            Method: GET
