---
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Enter 'dev' or 'prod'. Default 'dev'.
Resources:
  AdventurioApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}
      DefinitionUri: ./specs/openapi.yaml
      Variables:
        PostGamesFunction: !Ref PostGamesFunction
        GetGameFunction: !Ref GetGameFunction
  PostGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "post-games-function-${Stage}"
      Runtime: python3.7
      Handler: index.handler
      CodeUri: ./lambda/post-games/
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AdventurioApiGateway
            Path: /games
            Method: POST
      Environment:
        Variables:
          DYNAMODB-TABLE: !Ref GamesTable.TableName
  GetGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "get-game-function-${Stage}"
      Runtime: python3.7
      Handler: index.handler
      CodeUri: ./lambda/get-game/
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AdventurioApiGateway
            Path: /games/{gameId}
            Method: GET
      Environment:
        Variables:
          GAMES_TABLE: !Ref GamesTable
  GamesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "games-table-${Stage}"
      PrimaryKey:
        Name: id
        Type: String
