---
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Enter 'dev' or 'prod'. Default 'dev'.
Globals:
  Function:
    Environment:
      Variables:
        TEST_ENV:
        GAMES_TABLE: !Ref GamesTable
Resources:
  AdventurioApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Stage}
      DefinitionUri: ./specs/openapi.yaml
      Variables:
        PutGameFunction: !Ref PutGameFunction
        GetGameFunction: !Ref GetGameFunction
  PutGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "put-game-function-${Stage}"
      Runtime: python3.7
      Handler: index.handler
      CodeUri: ./lambda/put-game/
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AdventurioApiGateway
            Path: /games/{gameId}
            Method: PUT
  GetGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "get-game-function-${Stage}"
      Runtime: python3.7
      Handler: index.handler
      CodeUri: ./lambda/get-game/
      Events:
        PostPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref AdventurioApiGateway
            Path: /games/{gameId}
            Method: GET
  GamesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "adventurio-games-${Stage}"
      PrimaryKey:
        Name: id
        Type: String
