---
Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Enter dev, test or prod.
Resources:
  AdventurioUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        UnusedAccountValidityDays: 7
      Policies:
        PasswordPolicy:
          MinimumLength: 10
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      UsernameAttributes:
        - email
      UserPoolName: adventurio-${Env}
      UserPoolTags:
        String: adventurio-user-pool
