---
openapi: 3.0.2
info:
  version: "0.9"
  title: adventurio
  description: "Get or post info about Adventürio games."
  contact:
    name: "Tobias Rudin"
    email: "t.rudin@gmail.com"
paths:
  /games/{gameId}:
    put:
      summary: Create a game
      operationId: createGames
      parameters:
        - name: gameId
          in: path
          required: true
          description: The id of the game to retrieve
          schema:
            type: string
            minLength: 36
            maxLength: 36
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Game"
      responses:
        "201":
          description: Resource created
        "204":
          description: Resource updated
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-amazon-apigateway-request-validators:
        basic:
          validateRequestBody: true
          validateRequestParameters: true
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-north-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-north-1:454263499388:function:${stageVariables.PutGameFunction}/invocations"
    get:
      summary: Information about an Adventürio game
      operationId: showGameById
      parameters:
        - name: gameId
          in: path
          required: true
          description: The id of the game to retrieve
          schema:
            type: string
            minLength: 36
            maxLength: 36
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: true
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-north-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-north-1:454263499388:function:${stageVariables.GetGameFunction}/invocations"
components:
  schemas:
    Game:
      required:
        - id
        - name
        - paths
        - startPos
      properties:
        id:
          type: string
          minLength: 36
          maxLength: 36
        name:
          type: string
        paths:
          type: array
          items:
            $ref: "#/components/schemas/Path"
        startPos:
          properties:
            long:
              type: string
            lat:
              type: string
    Path:
      type: array
      items:
        $ref: "#/components/schemas/Point"
    Point:
      properties:
        long:
          type: string
        lat:
          type: string
        question:
          type: string
          maxLength: 100
        timeUntilAnswer:
          type: string
        hints:
          type: array
          items:
            $ref: "#/components/schemas/Hint"
        answer:
          type: string
          maxLength: 20
    Hint:
      properties:
        timeUntilShown:
          type: string
        text:
          type: string
          maxLength: 100
    Error:
      required:
        - message
      properties:
        message:
          type: string